// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZeNWZP4Cj1w5LCrmfS1btuw6eqsto7Ic',
    appId: '1:138614129206:web:aa1d301cd3e1c5b5fa0e97',
    messagingSenderId: '138614129206',
    projectId: 'areea-60ed7',
    authDomain: 'areea-60ed7.firebaseapp.com',
    storageBucket: 'areea-60ed7.appspot.com',
    measurementId: 'G-GRV2S464G9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsVERukQIq0NXc_0LSxrOkWspEtjdLgV8',
    appId: '1:138614129206:android:d59d968c5996c0dbfa0e97',
    messagingSenderId: '138614129206',
    projectId: 'areea-60ed7',
    storageBucket: 'areea-60ed7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUAYdjLMWqlhsZVVnVJ_e4fWOIf4nrTNQ',
    appId: '1:138614129206:ios:e3bd2a0cb16f17fafa0e97',
    messagingSenderId: '138614129206',
    projectId: 'areea-60ed7',
    storageBucket: 'areea-60ed7.appspot.com',
    iosBundleId: 'com.example.areea',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUAYdjLMWqlhsZVVnVJ_e4fWOIf4nrTNQ',
    appId: '1:138614129206:ios:6a56b5e1708d7969fa0e97',
    messagingSenderId: '138614129206',
    projectId: 'areea-60ed7',
    storageBucket: 'areea-60ed7.appspot.com',
    iosBundleId: 'com.example.areea.RunnerTests',
  );
}
